fix: updated jenkinsfile for github release and its related files

diff --git a/Jenkinsfile.github b/Jenkinsfile.github
--- a/Jenkinsfile.github
+++ b/Jenkinsfile.github
@@ -1,24 +1,43 @@
-library(
-  identifier: 'jenkins-shared-library@master',
-  retriever: modernSCM(
-    [
-      $class: 'GitSCMSource',
-      remote: 'https://github.com/dhanarab/jenkins-pipeline-library.git'
-    ]
-  )
-)
+import groovy.json.JsonOutput
 
-githubOwner = 'AccelByte'
-githubRepo = 'accelbyte-csharp-sdk'
-githubSsh = 'dhanarab-sdkbuild-ssh'
-githubPat = 'dhanarab-sdkbuild-pat-github'
 bitbucketSsh = 'bitbucket-build-extend-ssh'
-
+githubOwner = 'AccelByte'
+githubRepo = 'accelbyte-csharp-modular-sdk-test2'
+githubSsh = 'accelbyte-sdk-sdkbuild-ssh'
+githubPat = 'accelbyte-sdk-sdkbuild-pat-github'
 githubUrl = "git@github.com:${githubOwner}/${githubRepo}.git"
+sdkName = "AccelByte C# Extend Modular SDK"
+
+def createGithubRelease(tag_name, prerelease = false, name = null, body = null) {
+  def request = ['tag_name': tag_name]
+  if (name) {
+    request['name'] = name
+  }
+  if (body) {
+    request['body'] = body
+  }
+  request['prerelease'] = prerelease
+
+  def requestBody = JsonOutput.toJson(request)
+  echo "Request Body: ${requestBody}"
+
+  def response = httpRequest(
+    url : "https://api.github.com/repos/${githubOwner}/${githubRepo}/releases",
+    httpMode: 'POST',
+    requestBody: requestBody,
+    contentType: 'APPLICATION_JSON',
+    authentication: githubPat,
+    validResponseCodes: '200:201,422'
+  )
+
+ if (response.getStatus() != 201) {
+    error("Failed to create GitHub release. Response code: ${response.getStatus()}. Response message: ${response.getContent()}")
+  }
+}
 
 pipeline {
   agent {
-    label "master"
+    label "justice-codegen-sdk"
   }
   stages {
     stage('Prepare') {
@@ -32,15 +51,14 @@ pipeline {
     }
     stage('Push') {
       when {
-        expression { 
+        expression {
           return params.ACTION == 'PUSH'
         }
       }
       steps {
         script {
-          sh "git checkout master"
-          sshagent(credentials: [githubSsh])
-          {
+          sh 'git checkout master'
+          sshagent(credentials: [githubSsh]) {
             sh "git push ${githubUrl} HEAD:main"
           }
         }
@@ -48,66 +66,102 @@ pipeline {
     }
     stage('Release') {
       when {
-        expression { 
+        expression {
           return params.ACTION == 'PUSH+RELEASE'
         }
       }
       steps {
         script {
-          if (params.RELEASE_NOTE ==~ /(?s).*@[A-Za-z0-9_-]+@.*/)
-          {
+          releaseNote = params.RELEASE_NOTE
+
+          if (params.AGS_VERSION != "None") {
+            releaseNote = releaseNote.replace('@VERSION@', params.AGS_VERSION)
+          }
+
+          if (releaseNote ==~ /(?s).*@[A-Za-z0-9_-]+@.*/) {
             echo 'Release note still contains one or more template placeholders e.g. @VERSION@, etc. Please check.'
             sh 'false' // Fail this job
           }
-          sh "git checkout ${params.RELEASE_BRANCH}"
-          sshagent(credentials: [githubSsh])
-          {
-            if (params.RELEASE_BRANCH == "master") {
+
+          //sh "git checkout ${params.RELEASE_BRANCH}"
+          sh "git checkout CG-1393-pre-release-test-2"
+          sshagent(credentials: [githubSsh]) {
+            if (params.RELEASE_BRANCH == 'master') {
+              
+              echo "Check if tag `ags/v${params.AGS_VERSION}` is exists"
+              def tagCheck = sh(script: "git tag | grep 'ags/v${params.AGS_VERSION}'", returnStdout: true, returnStatus: true)
+              if (tagCheck == "") {
+                echo "AGS version tag 'ags/v${params.AGS_VERSION}' does not exists in source repository." 
+                sh 'false' // Fail this job
+              }
+
+              echo 'Push bitbucket master to github main'
               sh "git push ${githubUrl} HEAD:main"
-            }
-            else {
+
+              echo "Tag github main with ags version"
+              sh "git push ${githubUrl} 'ags/v${params.AGS_VERSION}'"
+
+              echo "Get all tags related to `ags/v${params.AGS_VERSION}` and push them"
+              sh "git tag --contains \$(git rev-list -n 1 'ags/v${params.AGS_VERSION}') | grep -v 'ags/v${params.AGS_VERSION}' | xargs -I{} sh -c 'git push ${githubUrl} '{}' || exit 255'"
+
+              //do github release 
+              releaseName = "${sdkName} for AGS v${params.AGS_VERSION}"
+              createGithubRelease("ags/v${params.AGS_VERSION}", params.IS_PRERELEASE, releaseName, releaseNote)
+
+              //do nuget release
+              sh "make pack"
+              sh "make pack_pick AGS_VER=${params.AGS_VERSION}"
+
+              //Zip nuget packaged files as job artifact
+              zip zipFile: "csharp_modular_sdk_ags_${params.AGS_VERSION}.zip", dir: "./publish_pick", overwrite: true, archive: true
+
+              withCredentials([usernamePassword(credentialsId: 'nuget-accelbyte-csharp-sdk', passwordVariable: 'NUGET_TOKEN', usernameVariable: 'NUGET_EMAIL')]) {
+                // sh "make pack_push_only NUGET_API_KEY=\$NUGET_TOKEN"
+              }
+
+              echo "Clear"
+
+            } else {
               sh "git push ${githubUrl} HEAD:${params.RELEASE_BRANCH}"
+              //Point release will be implemented later.
             }
-            sh "git push ${githubUrl} ${params.RELEASE_TAG}"
-            
           }
-          github.createRelease(githubPat, githubOwner, githubRepo, params.RELEASE_TAG, params.RELEASE_TAG, params.RELEASE_NOTE)
         }
       }
     }
     stage('Pull') {
       when {
-        expression { 
+        expression {
           return params.ACTION == 'PULL'
         }
       }
       steps {
         script {
-          sh "git checkout master"
+          sh 'git checkout master'
           sshagent(credentials: [githubSsh])
           {
             sh "git pull ${githubUrl} main"
           }
           sshagent(credentials: [bitbucketSsh])
           {
-            sh "git push"
+            sh 'git push'
           }
         }
       }
     }
   }
-  post {
-    failure {
-      script {
-        message = """
-            :no_entry: <${env.BUILD_URL}|${env.JOB_NAME}-${env.BUILD_NUMBER}> *failed*
-            
-            |*Action*
-            |${params.ACTION}
-            
-            |""".stripMargin()
-        slackSend(channel: "#activity-justice-codegen-modular-sdk", color: '#FF0000', message: message)
-      }
-    }
-  }
+//  post {
+//    failure {
+//      script {
+//        message = """
+//            :no_entry: <${env.BUILD_URL}|${env.JOB_NAME}-${env.BUILD_NUMBER}> *failed*
+//
+//            |*Action*
+//            |${params.ACTION}
+//
+//            |""".stripMargin()
+//        slackSend(channel: '#activity-justice-codegen-modular-sdk', color: '#FF0000', message: message)
+//      }
+//    }
+//  }
 }
